//Function 1
function check1() {

  var result1 = document.getElementById('result1');
  var q1 = Number(document.quiz1.radioSetOne.value) + Number(document.quiz1.radioSetTwo.value) + Number(document.quiz1.radioSetThree.value) + Number(document.quiz1.radioSetFour.value) + Number(document.quiz1.radioSetFive.value) + Number(document.quiz1.radioSetSix.value) + Number(document.quiz1.radioSetSeven.value) + Number(document.quiz1.radioSetEight.value) + Number(document.quiz1.radioSetNine.value) + Number(document.quiz1.radioSetTen.value) + Number(document.quiz1.radioSetEleven.value) + Number(document.quiz1.radioSetTwelve.value) + Number(document.quiz1.radioSetThirteen.value) + Number(document.quiz1.radioSetFourteen.value) + Number(document.quiz1.radioSetFifteen.value) +  Number(document.quiz1.radioSetSixteen.value) + Number(document.quiz1.radioSetSeventeen.value) + Number(document.quiz1.radioSetEighteen.value) + Number(document.quiz1.radioSetNineteen.value) + Number(document.quiz1.radioSetTwenty.value) + Number(document.quiz1.radioSetTwentyOne.value) + Number(document.quiz1.radioSetTwentyTwo.value) + Number(document.quiz1.radioSetTwentyThree.value) + Number(document.quiz1.radioSetTwentyFour.value) ;
  if (q1>=76 && q1<=100) {
    result1.textContent= "Your Result: " + q1 + "!!" + " High (76-100) You face significant ongoing challenges with managing your emotions. You struggle with tolerating your feelings and at times you may feel emotionally overwhelmed or out of control. It may be difficult for you to control your behaviors in moments when you are emotionally triggered. Your emotionally driven behaviors may be negatively impacting your relationships. Working with a therapist may help you identify and understand your emotions as well as develop skills for coping.";

  }
  else if (q1>=51 && q1<=75) {
    result1.textContent= "Your Result: " + q1 + "!!" + " Moderate (51-75) You face moderate challenges with managing your emotions. Your score suggests that you may experience your emotions as overwhelming and have difficulty with tolerating or understanding your emotional experiences. It may be difficult for you to recognize or articulate your feelings and needs in moments when you are emotionally activated. Working with a therapist may help you identify and understand your emotions as well as develop skills for coping.";
  }
  else if (q1>=26 && q1<=50) {
    result1.textContent= "Your Result: " + q1 + "!!" + " Well-Balanced (26-50) Your emotions are generally well balanced. Sometimes you may experience your emotions as overwhelming, but this doesn’t lead to negative consequences or significant negative impact in your daily life. You may wish to see a therapist if you have specific concerns that occasionally throw you off balance.";
  }
  else {
    result1.textContent= "Your Result: " + q1 + "!!" + " Low (0-25) Your emotional reactivity score is low. Your score suggests that you are able to tolerate and cope adaptively with your emotions. Your emotions are generally well balanced. You may wish to see a therapist if you have specific concerns that occasionally through you off balance."
  }
}

//Function 2
function check2() {

  var result2 = document.getElementById('result2');
  var q2 = Number(document.quiz2.radioSetOne.value) + Number(document.quiz2.radioSetTwo.value) + Number(document.quiz2.radioSetThree.value) + Number(document.quiz2.radioSetFour.value) + Number(document.quiz2.radioSetFive.value) + Number(document.quiz2.radioSetSix.value) + Number(document.quiz2.radioSetSeven.value) + Number(document.quiz2.radioSetEight.value) + Number(document.quiz2.radioSetNine.value) + Number(document.quiz2.radioSetTen.value) + Number(document.quiz2.radioSetEleven.value) + Number(document.quiz2.radioSetTwelve.value) + Number(document.quiz2.radioSetThirteen.value) + Number(document.quiz2.radioSetFourteen.value) + Number(document.quiz2.radioSetFifteen.value) +  Number(document.quiz2.radioSetSixteen.value) + Number(document.quiz2.radioSetSeventeen.value) + Number(document.quiz2.radioSetEighteen.value) + Number(document.quiz2.radioSetNineteen.value) + Number(document.quiz2.radioSetTwenty.value) + Number(document.quiz2.radioSetTwentyOne.value) + Number(document.quiz2.radioSetTwentyTwo.value) + Number(document.quiz2.radioSetTwentyThree.value) + Number(document.quiz2.radioSetTwentyFour.value) + Number(document.quiz2.radioSetTwentyFive.value) + Number(document.quiz2.radioSetTwentySix.value) + Number(document.quiz2.radioSetTwentySeven.value) + Number(document.quiz2.radioSetTwentyEight.value) + Number(document.quiz2.radioSetTwentyNine.value) + Number(document.quiz2.radioSetThirty.value) + Number(document.quiz2.radioSetThirtyOne.value) + Number(document.quiz2.radioSetThirtyTwo.value) + Number(document.quiz2.radioSetThirtyThree.value) + Number(document.quiz2.radioSetThirtyFour.value) + Number(document.quiz2.radioSetThirtyFive.value) + Number(document.quiz2.radioSetThirtySix.value) + Number(document.quiz2.radioSetThirtySeven.value) + Number(document.quiz2.radioSetThirtyEight.value) + Number(document.quiz2.radioSetThirtyNine.value) + Number(document.quiz2.radioSetFourty.value) + Number(document.quiz2.radioSetFourtyOne.value) + Number(document.quiz2.radioSetFourtyTwo.value) + Number(document.quiz2.radioSetFourtyThree.value) + Number(document.quiz2.radioSetFourtyFour.value) + Number(document.quiz2.radioSetFourtyFive.value) + Number(document.quiz2.radioSetFourtySix.value) + Number(document.quiz2.radioSetFourtySeven.value) + Number(document.quiz2.radioSetFourtyEight.value) + Number(document.quiz2.radioSetFourtyNine.value) + Number(document.quiz2.radioSetFifty.value) + Number(document.quiz2.radioSetFiftyOne.value) + Number(document.quiz2.radioSetFiftyTwo.value) + Number(document.quiz2.radioSetFiftyThree.value) + Number(document.quiz2.radioSetFiftyFour.value) + Number(document.quiz2.radioSetFiftyFive.value) ;
  if (q2>=165 && q2<=220) {
    result2.textContent= "Your Result: " + q2 + "!!" + " High (165-220) You face significant ongoing challenges in your relationships. You may struggle with expressing your feelings, making requests, or making a commitment to a romantic partner. You might feel ambivalent or unsatisfied in many of your relationships. You’re yearning for healthier and more effective relationships, but you are unclear as to what steps to take to improve them. You may struggle with connecting with others and creating appropriate boundaries and interdependence in your relationships. You might feel conflicted about how to create a balance of taking care of yourself in relationships, while still taking care of others and balancing the needs of others and your own. You struggle with feelings of ambivalence in relationships and may find it difficult to identify when you need to spend time with others and when you need to spend time alone. These conflicts may be having a negative impact on your relationships. Working with a therapist can help you identify and understand the barriers that stop you from having the healthy relationships you desire, as well as develop effective coping skills to promote more fulfilling and meaningful relationships.";

  }
  else if (q2>=110 && q2<=164) {
    result2.textContent= "Your Result: " + q2 + "!!" + " Moderate (110-164) You face moderate challenges in your relationships. Your score suggests that you feel dissatisfied in some of your relationships and that you long to build stronger more fulfilling connections with others. You may be yearning for healthier and more effective relationships, but you are unclear as to what steps to take to improve them. You may struggle with connecting with others and creating appropriate boundaries and interdependence in your relationships. These conflicts might be having a negative impact on your relationships. Working with a therapist can help you identify unhelpful patterns in your relationships, understand the barriers that stop you from having the healthy relationships you desire, and develop the necessary coping skills to develop more fulfilling and meaningful relationships.";
  }
  else if (q2>=59 && q2<=109) {
    result2.textContent= "Your Result: " + q2 + "!!" + " Well-Balanced (59-109) Your relationships are generally well balanced. Sometimes you may experience conflict in your relationships, but it may not lead to significant negative consequences in your relationships or a significant negative impact in your daily life. You may wish to see a therapist if you have specific concerns that occasionally throw you off balance or if you wish to identify certain relationship patterns, more specifically, in order to improve your relationships.";
  }
  else {
    result2.textContent= "Your Result: " + q2 + "!!" + " Low (0-58) Your interpersonal problems score is low. Your score suggests that you are able to cope effectively in your relationships and build intimate long lasting connections. Your relationships are generally well balanced. You may wish to see a therapist if you have specific concerns that occasionally throw you off balance or if you wish to identify certain relationship patterns, more specifically, in order to improve your relationships."
  }
}

//Function 3
function check3() {

  var result3 = document.getElementById('result3');
  var q3 = Number(document.quiz3.radioSetOne.value) + Number(document.quiz3.radioSetTwo.value) + Number(document.quiz3.radioSetThree.value) + Number(document.quiz3.radioSetFour.value) + Number(document.quiz3.radioSetFive.value) + Number(document.quiz3.radioSetSix.value) + Number(document.quiz3.radioSetSeven.value) + Number(document.quiz3.radioSetEight.value) + Number(document.quiz3.radioSetNine.value) + Number(document.quiz3.radioSetTen.value) + Number(document.quiz3.radioSetEleven.value) + Number(document.quiz3.radioSetTwelve.value) + Number(document.quiz3.radioSetThirteen.value) + Number(document.quiz3.radioSetFourteen.value) + Number(document.quiz3.radioSetFifteen.value) ;
  if (q3>=31 && q3<=45) {
    result3.textContent= "Your Result: " + q3 + "!!" + " High (31-45) A score in this range suggests that you may be experiencing a high degree of job stress and dissatisfaction. You are highly dissatisfied with your job and may be experiencing high levels of burnout. You may feel unproductive or under challenged at work. You may not enjoy your relationship with your coworkers. You may not have enough freedom or flexibility in your job. You may have a sense that you would be happier on a different career path, but you feel unclear about what steps to take. Working with a therapist may help you identify your career options and assess your needs. Your therapist can help you explore what’s important to you and what kind of work tasks and careers you are attracted to, and help you overcome the barriers that are getting in the way of finding your ideal job.";

  }
  else if (q3>=21 && q3<=30) {
    result3.textContent= "Your Result: " + q3 + "!!" + " Moderate (21-30) A score in this range suggests that you may be experiencing a moderate degree of job stress. Your score indicates a moderate level of job dissatisfaction. You may be feeling ambivalent about whether this is the best job for you now or in the long run. You may not feel adequately challenged, appreciated, or valued at your job. You may feel a lack of freedom or flexibility at your job, which leads to feeling overwhelmed. You may have a sense that you would be happier on a different career path, but you feel unclear about steps to take. Working with a therapist may help you identify your career options and assess your needs. Your therapist can help you explore what’s important to you and what kind of work tasks and careers you are attracted to, and help you overcome the barriers that are getting in the way of finding your ideal job.";
  }
  else {
    result3.textContent= "Your Result: " + q3 + "!!" + " Low (0-20) A score in this range suggests that you’re experiencing little or no symptoms of job stress. Your score indicates that you are generally satisfied and content with your job. Your job is providing you with a sense of meaning and purpose. It also provides you with a good balance of challenge and productivity. You may wish to meet with a therapist if you have specific concerns about your career that you would like to further explore or if you would like to identify strategies for increasing job satisfaction."
  }
}
//Function 4
function check4() {

  var result4 = document.getElementById('result4');
  var q4 = Number(document.quiz4.radioSetOne.value) + Number(document.quiz4.radioSetTwo.value) + Number(document.quiz4.radioSetThree.value) + Number(document.quiz4.radioSetFour.value) + Number(document.quiz4.radioSetFive.value) + Number(document.quiz4.radioSetSix.value) + Number(document.quiz4.radioSetSeven.value) + Number(document.quiz4.radioSetEight.value) + Number(document.quiz4.radioSetNine.value) + Number(document.quiz4.radioSetTen.value) + Number(document.quiz4.radioSetEleven.value) + Number(document.quiz4.radioSetTwelve.value) + Number(document.quiz4.radioSetThirteen.value) + Number(document.quiz4.radioSetFourteen.value) + Number(document.quiz4.radioSetFifteen.value) +  Number(document.quiz4.radioSetSixteen.value) + Number(document.quiz4.radioSetSeventeen.value) + Number(document.quiz4.radioSetEighteen.value) + Number(document.quiz4.radioSetNineteen.value) + Number(document.quiz4.radioSetTwenty.value) + Number(document.quiz4.radioSetTwentyOne.value) + Number(document.quiz4.radioSetTwentyTwo.value) + Number(document.quiz4.radioSetTwentyThree.value) + Number(document.quiz4.radioSetTwentyFour.value) + Number(document.quiz4.radioSetTwentyFive.value) + Number(document.quiz4.radioSetTwentySix.value) + Number(document.quiz4.radioSetTwentySeven.value) + Number(document.quiz4.radioSetTwentyEight.value) + Number(document.quiz4.radioSetTwentyNine.value) + Number(document.quiz4.radioSetThirty.value) ;
  if (q4>=91 && q4<=120) {
    result4.textContent= "Your Result: " + q4 + "!!" + " High (91-120) Your self-compassion score is high. Your score suggests that you are able to tolerate and cope well with negative emotions and the challenges you face. You are able to stay present and curious with your internal experiences. You typically treat yourself with loving-kindness and compassion during difficult moments. Your emotions are well balanced. You may wish to see a therapist if you have specific concerns that occasionally throw you off balance or if you would like to learn more tools and strategies for cultivating and building self-compassion.";

  }
  else if (q4>=61 && q4<=90) {
    result4.textContent= "Your Result: " + q4 + "!!" + " Moderate (61-90) Your self-compassion score is moderate. Your score indicates that you are able to cope effectively with struggles that show up and that your emotions are generally well balanced. For the most part, you are able to treat yourself with loving-kindness and compassion during difficult moments. You are not likely to beat yourself up over mistakes and are quick to learn and grow from past failures. You may wish to see a therapist if you have specific concerns that occasionally throw you off balance or if you would like to learn more tools and strategies for cultivating and building self-compassion.";
  }
  else if (q4>=31 && q4<=60) {
    result4.textContent= "Your Result: " + q4 + "!!" + " Low to Moderate (31-60) Your self-compassion score is low to moderate. Your score suggests that you may struggle with tolerating negative emotions and staying compassionate and kind with yourself in difficult moments. You may become highly self-critical when faced with challenges and obstacles in daily life. You have put pressure on yourself to succeed and may believe that if you are hard on yourself when you make a mistake, then you will be less likely to make mistakes in the future. You may believe that you need to bully yourself into becoming a better person. Working with a therapist may help you cultivate a more accepting, loving, and kind stance toward yourself. Your therapist can teach you tools to build self-compassion and help you identify more effective strategies for coping in moments when you feel that you’ve made a mistake or failed.";
  }
  else {
    result4.textContent= "Your Result: " + q4 + "!!" + " Low (0-30) Your self-compassion score is low. Your score suggests that you have great difficulty tolerating negative emotions and staying compassionate and kind with yourself in difficult moments. You face significant ongoing challenges with self-criticism and perfectionism. You tend to beat yourself up and get self-critical when faced with challenges and obstacles in daily life. You have difficulty tolerating the idea of making a mistake. You have a belief that the harsher you are with yourself, the more likely it is that you will repair your mistakes or not make a mistake in the future. You believe that you need to bully yourself into becoming a better person. Working with a therapist may help you cultivate a more accepting, loving, and kind stance toward yourself. Your therapist can teach you tools to build self-compassion and help you identify more effective strategies for coping in moments when you feel that you’ve made a mistake or failed."
  }
}
//Function 5
function check5() {

  var result5 = document.getElementById('result5');
  var q5 = Number(document.quiz5.radioSetOne.value) + Number(document.quiz5.radioSetTwo.value) + Number(document.quiz5.radioSetThree.value) + Number(document.quiz5.radioSetFour.value) + Number(document.quiz5.radioSetFive.value) + Number(document.quiz5.radioSetSix.value) + Number(document.quiz5.radioSetSeven.value) + Number(document.quiz5.radioSetEight.value) + Number(document.quiz5.radioSetNine.value) + Number(document.quiz5.radioSetTen.value) + Number(document.quiz5.radioSetEleven.value) + Number(document.quiz5.radioSetTwelve.value) + Number(document.quiz5.radioSetThirteen.value) + Number(document.quiz5.radioSetFourteen.value) + Number(document.quiz5.radioSetFifteen.value) +  Number(document.quiz5.radioSetSixteen.value) + Number(document.quiz5.radioSetSeventeen.value) + Number(document.quiz5.radioSetEighteen.value) + Number(document.quiz5.radioSetNineteen.value) + Number(document.quiz5.radioSetTwenty.value) + Number(document.quiz5.radioSetTwentyOne.value) + Number(document.quiz5.radioSetTwentyTwo.value) + Number(document.quiz5.radioSetTwentyThree.value) + Number(document.quiz5.radioSetTwentyFour.value) + Number(document.quiz5.radioSetTwentyFive.value) ;
  if (q5>=76 && q5<=100) {
    result5.textContent= "Your Result: " + q5 + "!!" + " High (76-100) You face significant ongoing challenges to managing your time, meeting deadlines, and accomplishing daily tasks. You typically delay and postpone important tasks that need to get done. You have difficulty prioritizing what’s important. You often struggle with delaying immediate gratification and with seeing the long-term perspective. Working with a therapist may help you develop the skills you need to manage your time, prioritize what’s important, and overcome the barriers that are getting in the way of you reaching your potential.";

  }
  else if (q5>=51 && q5<=75) {
    result5.textContent= "Your Result: " + q5 + "!!" + " Moderate (51-75) You face moderate challenges with avoidance and procrastination. You may struggle with managing your daily tasks and accomplishing and meeting deadlines. You tend to delay and postpone important tasks that need to get done. You may have difficulty prioritizing what’s important. You may struggle with delaying immediate gratification and with seeing the long-term outcomes. Working with a therapist may help you learn the time management skills that you need to reach your potential.";
  }
  else if (q5>=26 && q5<=50) {
    result5.textContent= "Your Result: " + q5 + "!!" + " Low to Moderate (26-50) Your score suggests a low to moderate level of procrastination. Your score indicates that while you may struggle with moments of procrastination, this does not lead to significant problems for you. You may occasionally put tasks off or delay them, you may have moments of feeling overwhelmed with your tasks, but it doesn’t generally lead to negative consequences in your daily life. You may wish to see a therapist if you have specific concerns related to time management that occasionally throw you off balance.";
  }
  else {
    result5.textContent= "Your Result: " + q5 + "!!" + " Low (0-25) Your low score indicates that you have no significant problems with procrastination. You are able to get tasks done efficiently and remain focused. You are able to accomplish your goals in a timely manner. You may wish to meet with a therapist if you have specific concerns related to time management that occasionally throw you off-balance."
  }
}
//Function 6
function check6() {

  var result6 = document.getElementById('result6');
  var q6 = Number(document.quiz6.radioSetOne.value) + Number(document.quiz6.radioSetTwo.value) + Number(document.quiz6.radioSetThree.value) + Number(document.quiz6.radioSetFour.value) + Number(document.quiz6.radioSetFive.value) + Number(document.quiz6.radioSetSix.value) + Number(document.quiz6.radioSetSeven.value) + Number(document.quiz6.radioSetEight.value) + Number(document.quiz6.radioSetNine.value) + Number(document.quiz6.radioSetTen.value) + Number(document.quiz6.radioSetEleven.value) + Number(document.quiz6.radioSetTwelve.value) + Number(document.quiz6.radioSetThirteen.value) + Number(document.quiz6.radioSetFourteen.value) + Number(document.quiz6.radioSetFifteen.value) +  Number(document.quiz6.radioSetSixteen.value) + Number(document.quiz6.radioSetSeventeen.value) + Number(document.quiz6.radioSetEighteen.value) + Number(document.quiz6.radioSetNineteen.value) + Number(document.quiz6.radioSetTwenty.value) ;
  if (q6>=60 && q6<=80) {
    result6.textContent= "Your Result: " + q6 + "!!" + " High (60-80) You're very satisfied and happy with your relationship. You feel very good about your relationship and your partner. You feel trust and safety with your partner, you feel that you can depend and rely on your partner, you feel a lot of support and love from your partner. Make sure that you let your partner know how satisfied they make you feel and continue reminding them how much you love and appreciate them.";

  }
  else if (q6>=20 && q6<=59) {
    result6.textContent= "Your Result: " + q6 + "!!" + " Moderate (20-59) You are ambivalent about your relationship. You're not satisfied, but it's not intolerable. You're not happy in your relationship, but you don't feel dissatisfied enough to leave. You should ask yourself what it is that is keeping you in this relationship? Is it that you have perfectionistic tendencies and unrelenting standards and expectations of relationships? Is it that you don't think you deserve to be happy in relationships? Is it that you're blaming yourself for feeling dissatisfied in the relationship? Figuring out why you are on the fence and getting yourself to a point where you feel more certain about where you stand in your relationship would be helpful to you. You may consider individual or couples therapy to help you get off the fence.";
  }
  else {
    result6.textContent= "Your Result: " + q6 + "!!" + " Low (0-58) You are very dissatisfied with your relationship. You don't feel happy in your relationship, you don't get your needs met, you don't feel loved or supported, you don't trust your partner, and you don't feel that you can rely on them. You should ask yourself what stops you from ending this relationship? Are you hoping that your partner will change? Do you not think that you deserve to be happy in relationships? Are you blaming yourself? Are you afraid of leaving your partner? Are you dependent on your partner? It would be helpful for you to understand why you're staying in a relationship that makes you feel so unhappy and unsatisfied. You may consider starting Cognitive Behavioral Therapy to assist you in improving your relationships."
  }
}
